fieldLayouts:
  5a443485-e5ef-49d2-883a-3690b08bbc27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 923e2fe4-f0cc-4f43-964c-426ec24f6056
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8826e0fa-1787-454d-97e5-957ed356239a # Bookmark List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b542f1f6-fa83-4d67-9766-43b9c186a11d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a245012-c6ce-4488-823e-0daa440d5360
        userCondition: null
handle: default
hasTitleField: true
name: 'Main Page'
section: 34db3768-6290-41d3-9dba-29db1f90bd9a # Storefront Display
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
