baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Flower Power Bookmarks'
primary: true
siteGroup: 40a793bb-ad73-4da9-be22-d9f1e49d823b # Flower Power Bookmarks
sortOrder: 1
