fieldLayouts:
  5db18590-ab54-4ed7-b1b2-593ce83c322f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7153d6b4-63a8-4a34-88e9-7752f4974084
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19c1657e-6c52-4c6c-a8e5-b7528055d800
        userCondition: null
fs: bookmarkPhotos
handle: photos
name: Photos
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
