columnSuffix: null
contentColumnType: string
fieldGroup: 06d774b2-e458-4593-b46d-d734e700c9d9 # Common
handle: imageDrawing
instructions: 'Sketched image of the bookmark for preload.'
name: 'Image Drawing'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:e23576ae-6c31-44c4-90ca-6edb93b75a5d' # Photos
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:e23576ae-6c31-44c4-90ca-6edb93b75a5d' # Photos
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:9216a446-a7a3-445e-be52-708ad70564e9' # Drawings
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
