columnSuffix: ozrxezzq
contentColumnType: integer(10)
fieldGroup: 06d774b2-e458-4593-b46d-d734e700c9d9 # Common
handle: price
instructions: 'Amount to charge in shopping cart.'
name: Price
searchable: false
settings:
  currency: USD
  defaultValue: 1000
  max: null
  min: 0
  showCurrency: true
  size: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Money
