columnSuffix: kbfthlcl
contentColumnType: integer(10)
fieldGroup: 06d774b2-e458-4593-b46d-d734e700c9d9 # Common
handle: stock
instructions: 'Number available in this design. Decreases when purchased.'
name: Stock
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
